<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260509063859 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE job_post (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, company_name VARCHAR(255) NOT NULL, location VARCHAR(255) NOT NULL, job_type VARCHAR(50) NOT NULL, work_mode VARCHAR(50) NOT NULL, category VARCHAR(100) NOT NULL, description TEXT NOT NULL, requirements TEXT DEFAULT NULL, application_deadline TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, cv_required BOOLEAN DEFAULT true NOT NULL, cover_letter_required BOOLEAN DEFAULT false NOT NULL, number_of_positions INT DEFAULT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, employer_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DD461ACC41CD9E7A ON job_post (employer_id)');
        $this->addSql('CREATE TABLE job_task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, task_name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, feasibility_level VARCHAR(50) NOT NULL, required_abilities JSON NOT NULL, job_post_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D5B2AD64D166B4B7 ON job_task (job_post_id)');
        $this->addSql('ALTER TABLE job_post ADD CONSTRAINT FK_DD461ACC41CD9E7A FOREIGN KEY (employer_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE job_task ADD CONSTRAINT FK_D5B2AD64D166B4B7 FOREIGN KEY (job_post_id) REFERENCES job_post (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE job_post DROP CONSTRAINT FK_DD461ACC41CD9E7A');
        $this->addSql('ALTER TABLE job_task DROP CONSTRAINT FK_D5B2AD64D166B4B7');
        $this->addSql('DROP TABLE job_post');
        $this->addSql('DROP TABLE job_task');
    }
}
