<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260510085811 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE employer_profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, company_name VARCHAR(255) DEFAULT NULL, industry VARCHAR(255) DEFAULT NULL, location VARCHAR(255) DEFAULT NULL, website VARCHAR(255) DEFAULT NULL, logo_url VARCHAR(500) DEFAULT NULL, description TEXT DEFAULT NULL, accessibility_statement TEXT DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C9BAD3B8A76ED395 ON employer_profile (user_id)');
        $this->addSql('ALTER TABLE employer_profile ADD CONSTRAINT FK_C9BAD3B8A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE employer_profile DROP CONSTRAINT FK_C9BAD3B8A76ED395');
        $this->addSql('DROP TABLE employer_profile');
    }
}
