<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260509132420 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create job_application table only';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE job_application (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(50) NOT NULL, application_file_name VARCHAR(255) DEFAULT NULL, application_original_name VARCHAR(255) DEFAULT NULL, recommendation_file_name VARCHAR(255) DEFAULT NULL, recommendation_original_name VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, candidate_id INT NOT NULL, job_post_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C737C68891BD8781 ON job_application (candidate_id)');
        $this->addSql('CREATE INDEX IDX_C737C688D166B4B7 ON job_application (job_post_id)');
        $this->addSql('ALTER TABLE job_application ADD CONSTRAINT FK_C737C68891BD8781 FOREIGN KEY (candidate_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE job_application ADD CONSTRAINT FK_C737C688D166B4B7 FOREIGN KEY (job_post_id) REFERENCES job_post (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE job_application DROP CONSTRAINT FK_C737C68891BD8781');
        $this->addSql('ALTER TABLE job_application DROP CONSTRAINT FK_C737C688D166B4B7');
        $this->addSql('DROP TABLE job_application');
    }
}